name: letsapp
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  shimmer: ^1.1.1
  page_transition: ^1.1.5
  font_awesome_flutter: ^8.8.1
  provider: ^4.1.3
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2
  maps_curved_line: ^0.1.1
  maps_toolkit: ^1.1.0
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/



